#!/bin/sh
set -eu
psql --set=ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=runtime_password="$GATEWAY_RUNTIME_DB_PASSWORD" \
  --set=worker_password="$GATEWAY_WORKER_DB_PASSWORD" <<'SQL'
CREATE ROLE gateway_runtime LOGIN PASSWORD :'runtime_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE gateway_worker LOGIN PASSWORD :'worker_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION BYPASSRLS;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
SQL
